### PR TITLE
amp_var_est added

### PR DESCRIPTION
**Pull request by mike123666**
amp_var_est OOT module is added. The installation should be the same as that of the original anastas/gr-cdma, except for changing the prefix in **cdma_parameters.py**

### CODE REVIEW

**Comment by anastas** [comment]
As you can see on your github account your commit says that there are 22 files that have been changed. This is because you have changed MORE files than the ones relating to the amp_var_estimator block.

I cannot check each and every file to see what I should merge and what not....

Here is what you need to do:

I will close (reject) this pull request.
You will have to download a FRESH version of gr-cdma from this site,
make ONLY the necessary changes required for adding the amp_var block and then you will resubmit the pull request

**Comment by anastas** [comment]
Also I notice that you

**Comment by anastas** [comment]
Also I notice that you have added to your commit unneeded crap files (such as the ones that end with ~). This is a mistake. Git need not keep track of these temporary files and they cluter the code.
Please do not include such files when you commit your changes...

**Comment by mike123666** [comment]
Oh I should have made a commit before building or installing the block. I've made a new pull request and there are 8 changes in the commit, mainly new added source files and automatically edited cmakelist files.

**Pull request closed without merging**
